# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Build matrix options
matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
  fast_finish: true
